(cl:in-package realm_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CAMERA_ID-VAL
          CAMERA_ID
          STAGE_ID-VAL
          STAGE_ID
          TIMESTAMP-VAL
          TIMESTAMP
          IMAGEDATA-VAL
          IMAGEDATA
          CAMERA_MODEL-VAL
          CAMERA_MODEL
          ORIENTATION-VAL
          ORIENTATION
          GPSDATA-VAL
          GPSDATA
          SPARSE_CLOUD-VAL
          SPARSE_CLOUD
          DEPTHMAP-VAL
          DEPTHMAP
          SURFACE_MODEL-VAL
          SURFACE_MODEL
          ORTHOPHOTO-VAL
          ORTHOPHOTO
          HEADING-VAL
          HEADING
          VISUAL_POSE-VAL
          VISUAL_POSE
          GEOREFERENCE-VAL
          GEOREFERENCE
          DO_RESET-VAL
          DO_RESET
          HAS_ACCURATE_POSE-VAL
          HAS_ACCURATE_POSE
          IS_KEYFRAME-VAL
          IS_KEYFRAME
          IS_GEOREFERENCED-VAL
          IS_GEOREFERENCED
          IS_SURFACE_ELEVATED-VAL
          IS_SURFACE_ELEVATED
))