// Generated by gencpp from file realm_msgs/CvGridMap.msg
// DO NOT EDIT!


#ifndef REALM_MSGS_MESSAGE_CVGRIDMAP_H
#define REALM_MSGS_MESSAGE_CVGRIDMAP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <sensor_msgs/Image.h>

namespace realm_msgs
{
template <class ContainerAllocator>
struct CvGridMap_
{
  typedef CvGridMap_<ContainerAllocator> Type;

  CvGridMap_()
    : header()
    , resolution(0.0)
    , pos()
    , length_x(0.0)
    , length_y(0.0)
    , layers()
    , data()  {
    }
  CvGridMap_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , resolution(0.0)
    , pos(_alloc)
    , length_x(0.0)
    , length_y(0.0)
    , layers(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _resolution_type;
  _resolution_type resolution;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _pos_type;
  _pos_type pos;

   typedef double _length_x_type;
  _length_x_type length_x;

   typedef double _length_y_type;
  _length_y_type length_y;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _layers_type;
  _layers_type layers;

   typedef std::vector< ::sensor_msgs::Image_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::sensor_msgs::Image_<ContainerAllocator> >> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::realm_msgs::CvGridMap_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realm_msgs::CvGridMap_<ContainerAllocator> const> ConstPtr;

}; // struct CvGridMap_

typedef ::realm_msgs::CvGridMap_<std::allocator<void> > CvGridMap;

typedef boost::shared_ptr< ::realm_msgs::CvGridMap > CvGridMapPtr;
typedef boost::shared_ptr< ::realm_msgs::CvGridMap const> CvGridMapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realm_msgs::CvGridMap_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realm_msgs::CvGridMap_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::realm_msgs::CvGridMap_<ContainerAllocator1> & lhs, const ::realm_msgs::CvGridMap_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.resolution == rhs.resolution &&
    lhs.pos == rhs.pos &&
    lhs.length_x == rhs.length_x &&
    lhs.length_y == rhs.length_y &&
    lhs.layers == rhs.layers &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::realm_msgs::CvGridMap_<ContainerAllocator1> & lhs, const ::realm_msgs::CvGridMap_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace realm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::realm_msgs::CvGridMap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realm_msgs::CvGridMap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realm_msgs::CvGridMap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realm_msgs::CvGridMap_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realm_msgs::CvGridMap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realm_msgs::CvGridMap_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realm_msgs::CvGridMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "51dea13d439405588b5af32df1e176e3";
  }

  static const char* value(const ::realm_msgs::CvGridMap_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x51dea13d43940558ULL;
  static const uint64_t static_value2 = 0x8b5af32df1e176e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::realm_msgs::CvGridMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realm_msgs/CvGridMap";
  }

  static const char* value(const ::realm_msgs::CvGridMap_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realm_msgs::CvGridMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Header for time and frame\n"
"Header header\n"
"\n"
"# CvGridMap uni resolution in x-/y-dir\n"
"float64 resolution\n"
"\n"
"# CvGridMap position of roi\n"
"geometry_msgs/Point pos\n"
"\n"
"# CvGridMap length of roi in x\n"
"float64 length_x\n"
"\n"
"# CvGridMap length of roi in y\n"
"float64 length_y\n"
"\n"
"# CvGridMap layer names\n"
"string[] layers\n"
"\n"
"# CvGridMap layer data\n"
"sensor_msgs/Image[] data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
;
  }

  static const char* value(const ::realm_msgs::CvGridMap_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realm_msgs::CvGridMap_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.resolution);
      stream.next(m.pos);
      stream.next(m.length_x);
      stream.next(m.length_y);
      stream.next(m.layers);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CvGridMap_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realm_msgs::CvGridMap_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realm_msgs::CvGridMap_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "resolution: ";
    Printer<double>::stream(s, indent + "  ", v.resolution);
    s << indent << "pos: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.pos);
    s << indent << "length_x: ";
    Printer<double>::stream(s, indent + "  ", v.length_x);
    s << indent << "length_y: ";
    Printer<double>::stream(s, indent + "  ", v.length_y);
    s << indent << "layers[]" << std::endl;
    for (size_t i = 0; i < v.layers.size(); ++i)
    {
      s << indent << "  layers[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.layers[i]);
    }
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALM_MSGS_MESSAGE_CVGRIDMAP_H
