// Generated by gencpp from file realm_msgs/Depthmap.msg
// DO NOT EDIT!


#ifndef REALM_MSGS_MESSAGE_DEPTHMAP_H
#define REALM_MSGS_MESSAGE_DEPTHMAP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <realm_msgs/Pinhole.h>
#include <geometry_msgs/Pose.h>
#include <sensor_msgs/Image.h>

namespace realm_msgs
{
template <class ContainerAllocator>
struct Depthmap_
{
  typedef Depthmap_<ContainerAllocator> Type;

  Depthmap_()
    : header()
    , camera_model()
    , pose()
    , data()  {
    }
  Depthmap_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , camera_model(_alloc)
    , pose(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::realm_msgs::Pinhole_<ContainerAllocator>  _camera_model_type;
  _camera_model_type camera_model;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::realm_msgs::Depthmap_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realm_msgs::Depthmap_<ContainerAllocator> const> ConstPtr;

}; // struct Depthmap_

typedef ::realm_msgs::Depthmap_<std::allocator<void> > Depthmap;

typedef boost::shared_ptr< ::realm_msgs::Depthmap > DepthmapPtr;
typedef boost::shared_ptr< ::realm_msgs::Depthmap const> DepthmapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realm_msgs::Depthmap_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realm_msgs::Depthmap_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::realm_msgs::Depthmap_<ContainerAllocator1> & lhs, const ::realm_msgs::Depthmap_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.camera_model == rhs.camera_model &&
    lhs.pose == rhs.pose &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::realm_msgs::Depthmap_<ContainerAllocator1> & lhs, const ::realm_msgs::Depthmap_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace realm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::realm_msgs::Depthmap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realm_msgs::Depthmap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realm_msgs::Depthmap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realm_msgs::Depthmap_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realm_msgs::Depthmap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realm_msgs::Depthmap_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realm_msgs::Depthmap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d0e44ab35357e17c520caeae09fad571";
  }

  static const char* value(const ::realm_msgs::Depthmap_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd0e44ab35357e17cULL;
  static const uint64_t static_value2 = 0x520caeae09fad571ULL;
};

template<class ContainerAllocator>
struct DataType< ::realm_msgs::Depthmap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realm_msgs/Depthmap";
  }

  static const char* value(const ::realm_msgs::Depthmap_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realm_msgs::Depthmap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "##################################################\n"
"# A message containing basic REALM depthmap data #\n"
"##################################################\n"
"\n"
"# (required) Header containing message meta data\n"
"std_msgs/Header header\n"
"\n"
"# (required) Camera_model containing pinhole parameters of capturing cam\n"
"realm_msgs/Pinhole camera_model\n"
"\n"
"# (required) Pose during acquisition\n"
"geometry_msgs/Pose pose\n"
"\n"
"# (required) Depth information\n"
"sensor_msgs/Image data\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: realm_msgs/Pinhole\n"
"#####################################################\n"
"# A message containing general pinhole camera model #\n"
"#####################################################\n"
"\n"
"# Image dimensions\n"
"std_msgs/UInt32 width\n"
"std_msgs/UInt32 height\n"
"\n"
"# Principal point\n"
"std_msgs/Float64 cx\n"
"std_msgs/Float64 cy\n"
"\n"
"# Focal length\n"
"std_msgs/Float64 fx\n"
"std_msgs/Float64 fy\n"
"\n"
"# Radial distortion parameters\n"
"std_msgs/Float64 k1\n"
"std_msgs/Float64 k2\n"
"std_msgs/Float64 p1\n"
"std_msgs/Float64 p2\n"
"std_msgs/Float64 k3\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/UInt32\n"
"uint32 data\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
;
  }

  static const char* value(const ::realm_msgs::Depthmap_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realm_msgs::Depthmap_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.camera_model);
      stream.next(m.pose);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Depthmap_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realm_msgs::Depthmap_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realm_msgs::Depthmap_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "camera_model: ";
    s << std::endl;
    Printer< ::realm_msgs::Pinhole_<ContainerAllocator> >::stream(s, indent + "  ", v.camera_model);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "data: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALM_MSGS_MESSAGE_DEPTHMAP_H
