// Generated by gencpp from file realm_msgs/GroundImageCompressed.msg
// DO NOT EDIT!


#ifndef REALM_MSGS_MESSAGE_GROUNDIMAGECOMPRESSED_H
#define REALM_MSGS_MESSAGE_GROUNDIMAGECOMPRESSED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/CompressedImage.h>
#include <sensor_msgs/NavSatFix.h>

namespace realm_msgs
{
template <class ContainerAllocator>
struct GroundImageCompressed_
{
  typedef GroundImageCompressed_<ContainerAllocator> Type;

  GroundImageCompressed_()
    : imagedata()
    , gpsdata()
    , scale(0.0)  {
    }
  GroundImageCompressed_(const ContainerAllocator& _alloc)
    : imagedata(_alloc)
    , gpsdata(_alloc)
    , scale(0.0)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::CompressedImage_<ContainerAllocator>  _imagedata_type;
  _imagedata_type imagedata;

   typedef  ::sensor_msgs::NavSatFix_<ContainerAllocator>  _gpsdata_type;
  _gpsdata_type gpsdata;

   typedef double _scale_type;
  _scale_type scale;





  typedef boost::shared_ptr< ::realm_msgs::GroundImageCompressed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realm_msgs::GroundImageCompressed_<ContainerAllocator> const> ConstPtr;

}; // struct GroundImageCompressed_

typedef ::realm_msgs::GroundImageCompressed_<std::allocator<void> > GroundImageCompressed;

typedef boost::shared_ptr< ::realm_msgs::GroundImageCompressed > GroundImageCompressedPtr;
typedef boost::shared_ptr< ::realm_msgs::GroundImageCompressed const> GroundImageCompressedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realm_msgs::GroundImageCompressed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realm_msgs::GroundImageCompressed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::realm_msgs::GroundImageCompressed_<ContainerAllocator1> & lhs, const ::realm_msgs::GroundImageCompressed_<ContainerAllocator2> & rhs)
{
  return lhs.imagedata == rhs.imagedata &&
    lhs.gpsdata == rhs.gpsdata &&
    lhs.scale == rhs.scale;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::realm_msgs::GroundImageCompressed_<ContainerAllocator1> & lhs, const ::realm_msgs::GroundImageCompressed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace realm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::realm_msgs::GroundImageCompressed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realm_msgs::GroundImageCompressed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realm_msgs::GroundImageCompressed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realm_msgs::GroundImageCompressed_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realm_msgs::GroundImageCompressed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realm_msgs::GroundImageCompressed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realm_msgs::GroundImageCompressed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1c6d3d69899b6565e069bc83ccb3ad99";
  }

  static const char* value(const ::realm_msgs::GroundImageCompressed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1c6d3d69899b6565ULL;
  static const uint64_t static_value2 = 0xe069bc83ccb3ad99ULL;
};

template<class ContainerAllocator>
struct DataType< ::realm_msgs::GroundImageCompressed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realm_msgs/GroundImageCompressed";
  }

  static const char* value(const ::realm_msgs::GroundImageCompressed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realm_msgs::GroundImageCompressed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# A message to handle georeferenced images projected to a ground plane\n"
"\n"
"# Projected image at ground level in ENU coordinate frame\n"
"sensor_msgs/CompressedImage imagedata\n"
"\n"
"# Global position of the image to be displayed. Upper left corner\n"
"sensor_msgs/NavSatFix gpsdata\n"
"\n"
"# Scale of warped image with [m / pixels]\n"
"float64 scale\n"
"\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/CompressedImage\n"
"# This message contains a compressed image\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"\n"
"string format        # Specifies the format of the data\n"
"                     #   Acceptable values:\n"
"                     #     jpeg, png\n"
"uint8[] data         # Compressed image buffer\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/NavSatFix\n"
"# Navigation Satellite fix for any Global Navigation Satellite System\n"
"#\n"
"# Specified using the WGS 84 reference ellipsoid\n"
"\n"
"# header.stamp specifies the ROS time for this measurement (the\n"
"#        corresponding satellite time may be reported using the\n"
"#        sensor_msgs/TimeReference message).\n"
"#\n"
"# header.frame_id is the frame of reference reported by the satellite\n"
"#        receiver, usually the location of the antenna.  This is a\n"
"#        Euclidean frame relative to the vehicle, not a reference\n"
"#        ellipsoid.\n"
"Header header\n"
"\n"
"# satellite fix status information\n"
"NavSatStatus status\n"
"\n"
"# Latitude [degrees]. Positive is north of equator; negative is south.\n"
"float64 latitude\n"
"\n"
"# Longitude [degrees]. Positive is east of prime meridian; negative is west.\n"
"float64 longitude\n"
"\n"
"# Altitude [m]. Positive is above the WGS 84 ellipsoid\n"
"# (quiet NaN if no altitude is available).\n"
"float64 altitude\n"
"\n"
"# Position covariance [m^2] defined relative to a tangential plane\n"
"# through the reported position. The components are East, North, and\n"
"# Up (ENU), in row-major order.\n"
"#\n"
"# Beware: this coordinate system exhibits singularities at the poles.\n"
"\n"
"float64[9] position_covariance\n"
"\n"
"# If the covariance of the fix is known, fill it in completely. If the\n"
"# GPS receiver provides the variance of each measurement, put them\n"
"# along the diagonal. If only Dilution of Precision is available,\n"
"# estimate an approximate covariance from that.\n"
"\n"
"uint8 COVARIANCE_TYPE_UNKNOWN = 0\n"
"uint8 COVARIANCE_TYPE_APPROXIMATED = 1\n"
"uint8 COVARIANCE_TYPE_DIAGONAL_KNOWN = 2\n"
"uint8 COVARIANCE_TYPE_KNOWN = 3\n"
"\n"
"uint8 position_covariance_type\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/NavSatStatus\n"
"# Navigation Satellite fix status for any Global Navigation Satellite System\n"
"\n"
"# Whether to output an augmented fix is determined by both the fix\n"
"# type and the last time differential corrections were received.  A\n"
"# fix is valid when status >= STATUS_FIX.\n"
"\n"
"int8 STATUS_NO_FIX =  -1        # unable to fix position\n"
"int8 STATUS_FIX =      0        # unaugmented fix\n"
"int8 STATUS_SBAS_FIX = 1        # with satellite-based augmentation\n"
"int8 STATUS_GBAS_FIX = 2        # with ground-based augmentation\n"
"\n"
"int8 status\n"
"\n"
"# Bits defining which Global Navigation Satellite System signals were\n"
"# used by the receiver.\n"
"\n"
"uint16 SERVICE_GPS =     1\n"
"uint16 SERVICE_GLONASS = 2\n"
"uint16 SERVICE_COMPASS = 4      # includes BeiDou.\n"
"uint16 SERVICE_GALILEO = 8\n"
"\n"
"uint16 service\n"
;
  }

  static const char* value(const ::realm_msgs::GroundImageCompressed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realm_msgs::GroundImageCompressed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.imagedata);
      stream.next(m.gpsdata);
      stream.next(m.scale);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GroundImageCompressed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realm_msgs::GroundImageCompressed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realm_msgs::GroundImageCompressed_<ContainerAllocator>& v)
  {
    s << indent << "imagedata: ";
    s << std::endl;
    Printer< ::sensor_msgs::CompressedImage_<ContainerAllocator> >::stream(s, indent + "  ", v.imagedata);
    s << indent << "gpsdata: ";
    s << std::endl;
    Printer< ::sensor_msgs::NavSatFix_<ContainerAllocator> >::stream(s, indent + "  ", v.gpsdata);
    s << indent << "scale: ";
    Printer<double>::stream(s, indent + "  ", v.scale);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALM_MSGS_MESSAGE_GROUNDIMAGECOMPRESSED_H
