// Generated by gencpp from file realm_msgs/ParameterChangeRequest.msg
// DO NOT EDIT!


#ifndef REALM_MSGS_MESSAGE_PARAMETERCHANGEREQUEST_H
#define REALM_MSGS_MESSAGE_PARAMETERCHANGEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace realm_msgs
{
template <class ContainerAllocator>
struct ParameterChangeRequest_
{
  typedef ParameterChangeRequest_<ContainerAllocator> Type;

  ParameterChangeRequest_()
    : name()
    , val()  {
    }
  ParameterChangeRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , val(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _val_type;
  _val_type val;





  typedef boost::shared_ptr< ::realm_msgs::ParameterChangeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realm_msgs::ParameterChangeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ParameterChangeRequest_

typedef ::realm_msgs::ParameterChangeRequest_<std::allocator<void> > ParameterChangeRequest;

typedef boost::shared_ptr< ::realm_msgs::ParameterChangeRequest > ParameterChangeRequestPtr;
typedef boost::shared_ptr< ::realm_msgs::ParameterChangeRequest const> ParameterChangeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realm_msgs::ParameterChangeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realm_msgs::ParameterChangeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::realm_msgs::ParameterChangeRequest_<ContainerAllocator1> & lhs, const ::realm_msgs::ParameterChangeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.val == rhs.val;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::realm_msgs::ParameterChangeRequest_<ContainerAllocator1> & lhs, const ::realm_msgs::ParameterChangeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace realm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::realm_msgs::ParameterChangeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realm_msgs::ParameterChangeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realm_msgs::ParameterChangeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realm_msgs::ParameterChangeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realm_msgs::ParameterChangeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realm_msgs::ParameterChangeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realm_msgs::ParameterChangeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "672fe963919628c6048bd6f60445c089";
  }

  static const char* value(const ::realm_msgs::ParameterChangeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x672fe963919628c6ULL;
  static const uint64_t static_value2 = 0x048bd6f60445c089ULL;
};

template<class ContainerAllocator>
struct DataType< ::realm_msgs::ParameterChangeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realm_msgs/ParameterChangeRequest";
  }

  static const char* value(const ::realm_msgs::ParameterChangeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realm_msgs::ParameterChangeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Name of the parameter\n"
"string name\n"
"\n"
"# Value of the parameter\n"
"# Must be parsed inside node\n"
"string val\n"
"\n"
;
  }

  static const char* value(const ::realm_msgs::ParameterChangeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realm_msgs::ParameterChangeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.val);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ParameterChangeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realm_msgs::ParameterChangeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realm_msgs::ParameterChangeRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "val: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.val);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALM_MSGS_MESSAGE_PARAMETERCHANGEREQUEST_H
