// Generated by gencpp from file realm_msgs/ParameterChange.msg
// DO NOT EDIT!


#ifndef REALM_MSGS_MESSAGE_PARAMETERCHANGE_H
#define REALM_MSGS_MESSAGE_PARAMETERCHANGE_H

#include <ros/service_traits.h>


#include <realm_msgs/ParameterChangeRequest.h>
#include <realm_msgs/ParameterChangeResponse.h>


namespace realm_msgs
{

struct ParameterChange
{

typedef ParameterChangeRequest Request;
typedef ParameterChangeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ParameterChange
} // namespace realm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realm_msgs::ParameterChange > {
  static const char* value()
  {
    return "1b0cde31d4f2ab3d28e7c08a4c6bd1f0";
  }

  static const char* value(const ::realm_msgs::ParameterChange&) { return value(); }
};

template<>
struct DataType< ::realm_msgs::ParameterChange > {
  static const char* value()
  {
    return "realm_msgs/ParameterChange";
  }

  static const char* value(const ::realm_msgs::ParameterChange&) { return value(); }
};


// service_traits::MD5Sum< ::realm_msgs::ParameterChangeRequest> should match
// service_traits::MD5Sum< ::realm_msgs::ParameterChange >
template<>
struct MD5Sum< ::realm_msgs::ParameterChangeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realm_msgs::ParameterChange >::value();
  }
  static const char* value(const ::realm_msgs::ParameterChangeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realm_msgs::ParameterChangeRequest> should match
// service_traits::DataType< ::realm_msgs::ParameterChange >
template<>
struct DataType< ::realm_msgs::ParameterChangeRequest>
{
  static const char* value()
  {
    return DataType< ::realm_msgs::ParameterChange >::value();
  }
  static const char* value(const ::realm_msgs::ParameterChangeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realm_msgs::ParameterChangeResponse> should match
// service_traits::MD5Sum< ::realm_msgs::ParameterChange >
template<>
struct MD5Sum< ::realm_msgs::ParameterChangeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realm_msgs::ParameterChange >::value();
  }
  static const char* value(const ::realm_msgs::ParameterChangeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realm_msgs::ParameterChangeResponse> should match
// service_traits::DataType< ::realm_msgs::ParameterChange >
template<>
struct DataType< ::realm_msgs::ParameterChangeResponse>
{
  static const char* value()
  {
    return DataType< ::realm_msgs::ParameterChange >::value();
  }
  static const char* value(const ::realm_msgs::ParameterChangeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALM_MSGS_MESSAGE_PARAMETERCHANGE_H
