// Generated by gencpp from file realm_msgs/ParameterChangeResponse.msg
// DO NOT EDIT!


#ifndef REALM_MSGS_MESSAGE_PARAMETERCHANGERESPONSE_H
#define REALM_MSGS_MESSAGE_PARAMETERCHANGERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace realm_msgs
{
template <class ContainerAllocator>
struct ParameterChangeResponse_
{
  typedef ParameterChangeResponse_<ContainerAllocator> Type;

  ParameterChangeResponse_()
    : success(false)
    , message()  {
    }
  ParameterChangeResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::realm_msgs::ParameterChangeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realm_msgs::ParameterChangeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ParameterChangeResponse_

typedef ::realm_msgs::ParameterChangeResponse_<std::allocator<void> > ParameterChangeResponse;

typedef boost::shared_ptr< ::realm_msgs::ParameterChangeResponse > ParameterChangeResponsePtr;
typedef boost::shared_ptr< ::realm_msgs::ParameterChangeResponse const> ParameterChangeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realm_msgs::ParameterChangeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realm_msgs::ParameterChangeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::realm_msgs::ParameterChangeResponse_<ContainerAllocator1> & lhs, const ::realm_msgs::ParameterChangeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::realm_msgs::ParameterChangeResponse_<ContainerAllocator1> & lhs, const ::realm_msgs::ParameterChangeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace realm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::realm_msgs::ParameterChangeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realm_msgs::ParameterChangeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realm_msgs::ParameterChangeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realm_msgs::ParameterChangeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realm_msgs::ParameterChangeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realm_msgs::ParameterChangeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realm_msgs::ParameterChangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::realm_msgs::ParameterChangeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::realm_msgs::ParameterChangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realm_msgs/ParameterChangeResponse";
  }

  static const char* value(const ::realm_msgs::ParameterChangeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realm_msgs::ParameterChangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"# True if parameter was set to value\n"
"bool success\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::realm_msgs::ParameterChangeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realm_msgs::ParameterChangeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ParameterChangeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realm_msgs::ParameterChangeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realm_msgs::ParameterChangeResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALM_MSGS_MESSAGE_PARAMETERCHANGERESPONSE_H
